### ISSUE TITLE
Wunderbar durability mode micro stutter when die.

### ISSUE THREAD

**Issue by dhaern** [Toxicom/toxiui#141] opened 2024-10-08 14:27 UTC
### Description
When I enable durability module in Wunderbar I get micro stutter/freeze every time I die and I lose durability (I guess deaths without durability penalty dont affect to this), not a big stutter but maybe 0.3-0.4 secs. Tested with durability module disabled and everything works normal. Tested vs durability ElvUI module and ElvUI durability module dont have this issue.

### Lua error

No LUA error, small performance issue.

### ToxiUI Status Report
![image](https://github.com/user-attachments/assets/de0f3965-3548-452f-a7c8-7004a849c020)

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Enable durability module in Wunderbar.
2. Go to a dungeon and suicide, check stutter in deaths vs bosses and normal packs. I tested in Tirna mythic 0 but you can check in other actual dungeons.
3. Compare vs the module disabled.

**Comment by Toxicom** [comment] 2024-11-13 20:33
What are your WunderBar's visibility settings? Is it visible in combat, too? @dhaern

**Comment by Toxicom** [comment] 2024-11-13 20:46
Testing this right now. Tested these conditions:
- WunderBar Hide in Combat
- WunderBar Show Always
- Durability module removed

In all cases I don't really notice a stutter. Even if it is there, it happens after you die, so honestly I don't see a big issue, as it does not matter at that point 😆 

Closing the issue as I can't reproduce this reliably.

**Closed as completed by Toxicom** 2024-11-13 20:46 UTC
