### ISSUE TITLE
ActionBar "Key Down" Effects WunderBar MicroMenu and Hearthstones

### ISSUE THREAD

**Issue by ArcheKnight** [Toxicom/toxiui#133] opened 2024-09-18 19:42 UTC
### Description
With the ActionBars setting "Key Down" toggled off the WunderBar "ToxiUI: MicroMenu" and  "ToxiUI: Hearthstone" modules do not allow clicking in any way. This doesn't seem to effect other modules even if I change their positions.

### Lua error
```lua
No error produced
```

### ToxiUI Status Report
Type `/tx status` in game and paste a screenshot of it here.
![image](https://github.com/user-attachments/assets/24260135-e475-4f90-87ee-c50f26e43cac)

### Screenshots
Screenshots often say more than words

### To reproduce
If this issue is describing a bug, include some steps to reproduce the behavior

1. Install ToxiUI using default ToxiUI install prompts
2. Change ElvUI ActionBars setting for "Key Down" to the off state
3. Click on the MicroMenu and Hearthstones modules on the WunderBar

**Comment by Toxicom** [comment] 2024-09-18 19:52
Duplicate of https://github.com/Toxicom/toxiui/issues/126

**Closed as completed by Toxicom** 2024-09-18 19:52 UTC
Labels: duplicate, wontfix
