### ISSUE TITLE
Missing Textures when using Syling Tracker

### ISSUE THREAD

**Issue by Krekot** [Toxicom/toxiui#18] opened 2022-11-13 07:54 UTC
### Description

When using Syling Tracker I get missing shadow textures. I contacted dev of Syling Tracker and he replied that it is problem with ToxiUi.

### Screenshots
Without Syling Tracker
![1](https://user-images.githubusercontent.com/580730/201511680-52fced85-1f6c-4132-8754-e2e524012445.png)

With Syling Tracker
![2](https://user-images.githubusercontent.com/580730/201511692-4f78a337-ef81-4bcc-b240-d1f2c943c0a0.png)

### Notes

You can check it on curseforge in comments: https://www.curseforge.com/wow/addons/sylingtracker#c92

He told that this bug is causing it:

```
Message: ...terface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua:156: attempt to index local 'mt' (a nil value)
Time: Sun Nov 13 01:09:28 2022
Count: 1
Stack: ...terface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua:156: attempt to index local 'mt' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua"]:156: in function `API'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua"]:212: in function `MetatableScan'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua"]:275: in function `Enable'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua"]:312: in function `callback'
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:285: in function `ContinueOutOfCombat'
[string "@Interface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua"]:309: in function <...terface/AddOns/ElvUI_ToxiUI/Modules/AddOns/Theme.lua:302>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:252: in function <...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua:250>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:170: in function <...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua:169>
[string "=[C]"]: ?
...
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Core.lua"]:125: in function `callback'
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:312: in function `ContinueAfter'
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:351: in function `ContinueAfterElvUIUpdate'
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Core.lua"]:101: in function <Interface/AddOns/ElvUI_ToxiUI/Core/Core.lua:99>
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:379: in function <...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua:374>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:170: in function <...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua:169>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:173: in function `TriggerEvent'
[string "@Interface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua"]:388: in function <...terface/AddOns/ElvUI_ToxiUI/Core/Functions/Event.lua:387>

Locals:
```

When this error occurs, the process for adding shadow effects stop. The fix cannot come from me, the developers of ToxiUI need to do a checking to be sure mt is not nil and avoid potential errors could stop the process.
`if not mt then return end`
is enough for fixing the issue.

### To reproduce

1.

### Acceptance criteria

-   [ ]

**Comment by Wolen** [comment] 2022-11-17 20:40
Potentially fixed with #19, waiting on Syling Tracker to update for confirmation.

**Comment by luiepandabeertv** [comment] 2023-05-10 10:39
Is still a problem?

**Comment by luiepandabeertv** [comment] 2023-05-10 14:23
The problem is no more. So this can be closed.

**Closed as completed** 2023-05-10 14:43 UTC
