### ISSUE TITLE
[BUG] VehicleBar: Taint

### ISSUE THREAD

**Issue by Toxicom** [Toxicom/toxiui#1] opened 2022-10-29 21:12 UTC
# Description
Discord report:
```lua
Message: ADDON_ACTION_BLOCKED: ElvUI_ToxiUI tried to call the protected function 'TXUIVehicleBar:SetPoint()'.
Time: Sun Oct  9 13:08:55 2022
Count: 155
Stack: ADDON_ACTION_BLOCKED: ElvUI_ToxiUI tried to call the protected function 'TXUIVehicleBar:SetPoint()'.
[string "@Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function SetPoint'
[string "@Interface\AddOns\ElvUI_ToxiUI\Core\Animations.lua"]:1014: in function `Update'
[string "@Interface\AddOns\ElvUI_ToxiUI\Core\Animations.lua"]:32: in function <Interface\AddOns\ElvUI_ToxiUI\Core\Animations.lua:29>

Locals: <none>
```

# Additional Information
- Discord link: https://discordapp.com/channels/769550106948141086/790546638548500520/1028761295069138985

**Comment by bagelbits** [comment] 2022-11-01 00:08
@Toxicom Is this fixed now with the Vehicle Bar changes?

It might be worthwhile to include `Steps to reproduce` because that Discord Link is broken for me now. :/

**Comment by Toxicom** [comment] 2022-11-01 00:09
Discord links to #contributor-chat, aka patreon. No steps were given hence the vague description:|

**Comment by RyadaProductions** [comment] 2022-12-02 16:01
This seems to be caused by doing the mounting cast for dragonflight mounts and then getting in combat while casting it. This cancels the mounting but also produced the error. (and resulting issues)
The new stacktrace on the newest version of ToxiUI is:
```6x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_ToxiUI' tried to call the protected function 'TXUIVehicleBar:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@ElvUI_ToxiUI/Core/Animations.lua"]:1014: in function `Update'
[string "@ElvUI_ToxiUI/Core/Animations.lua"]:32: in function <ElvUI_ToxiUI/Core/Animations.lua:29```

**Closed as completed** 2022-12-22 18:34 UTC
Labels: bug
