### ISSUE TITLE
Bugs encountered in Wintergrasp

### ISSUE THREAD

**Issue by xouqoa** [Toxicom/toxiui#34] opened 2023-01-22 02:52 UTC
### Description

I continually get these while in Wintergrasp, and I think they have popped up in Isle of Conquest as well before.

### Notes

It happens on every WG match for me.

![image](https://user-images.githubusercontent.com/3315900/213898340-648a414e-ce04-4abc-98e0-83410c9bed67.png)

### To reproduce

1. Play Wintergrasp? Gross, I know. I hate it too.

### Acceptance criteria

-   The text from the errors captured from Bugsack is attached. Hope that helps.

[1.txt](https://github.com/Toxicom/toxiui/files/10473612/1.txt)
[2.txt](https://github.com/Toxicom/toxiui/files/10473613/2.txt)
[3.txt](https://github.com/Toxicom/toxiui/files/10473614/3.txt)
[4.txt](https://github.com/Toxicom/toxiui/files/10473615/4.txt)

**Comment by Toxicom** [comment] 2023-07-19 20:42
Looks like duplicate of https://github.com/Toxicom/toxiui/issues/43
Closing this, since #43 is more detailed

**Closed as completed by Toxicom** 2023-07-19 20:42 UTC
Labels: bug
